spring.application.name=demo
spring.data.mongodb.uri=mongodb+srv://oscarm19021:Barcelona277353.@cluster0.8ukne.mongodb.net/database0?retryWrites=true&w=majority&appName=Cluster0
security.jwt.secret-key=pU8xJt9Lfj3KZz2QqY6cRpA9FgS7vXs9Ndq5R3eMbCc=
security.jwt.expiration=60000
logging.level.org.springframework.security=DEBUG
server.port=8081